[tool.briefcase]
project_name = "Kemono Downloader"
bundle = "com.voxdroid"
version = "3.5.0"
url = "https://github.com/VoxDroid/KemonoDownloader"
license.file = "LICENSE"
author = "VoxDroid"
author_email = "voxdroid@github.com"

[tool.briefcase.app.kemonodownloader]
formal_name = "KemonoDownloader"
description = "A cross-platform Python app built with PyQt6 to download posts and creator content from Kemono.su."
long_description = """A cross-platform Python app built with PyQt6 to download posts and creator content from Kemono.su. Supports concurrent downloads, file deduplication, and customizable settings."""
signing_identity = ""
icon = "assets/icons/KemonoDownloader"  

sources = [
    "src/kemonodownloader",
]

test_sources = [
    "tests",
]

requires = [
    "pyqt6",
    "requests",
    "beautifulsoup4", 
    "qtawesome",
    "packaging",
    "pillow",
    "fake-useragent"
]

test_requires = [
    "pytest",
]

[tool.briefcase.app.kemonodownloader.macOS]
universal_build = true
requires = [
    "std-nslog~=1.0.3",
]


[tool.briefcase.app.kemonodownloader.linux]
requires = [
]

[tool.briefcase.app.kemonodownloader.linux.system.debian]
system_requires = [
]

system_runtime_requires = [
    # Derived from https://doc.qt.io/qt-6/linux-requirements.html
    "libxext6",
    "libxrender1",
    "libx11-xcb1",
    "libxkbcommon-x11-0",
    "libxcb-image0",
    "libxcb-cursor0",
    "libxcb-shape0",
    "libxcb-randr0",
    "libxcb-xfixes0",
    "libxcb-sync1",
    "libxcb-icccm4",
    "libxcb-keysyms1",
    "libfontconfig1",
    "libsm6",
    "libice6",
    "libglib2.0-0",
    "libgl1",
    "libegl1",
    "libdbus-1-3",
]

[tool.briefcase.app.kemonodownloader.linux.system.rhel]
system_requires = [
]

system_runtime_requires = [
    "qt6-qtbase-gui",
]

[tool.briefcase.app.kemonodownloader.linux.system.suse]
system_requires = [
]

system_runtime_requires = [
    "libgthread-2_0-0",
    "libQt6Gui6",
]

[tool.briefcase.app.kemonodownloader.linux.system.arch]
system_requires = [
]

system_runtime_requires = [
    "qt6-base",
]

[tool.briefcase.app.kemonodownloader.linux.appimage]
manylinux = "manylinux_2_28"

system_requires = [
# ?? FIXME
]

linuxdeploy_plugins = [
]

[tool.briefcase.app.kemonodownloader.linux.flatpak]
flatpak_runtime = "org.kde.Platform"
flatpak_runtime_version = "6.7"
flatpak_sdk = "org.kde.Sdk"

[tool.briefcase.app.kemonodownloader.windows]
requires = [
]

# Mobile deployments
[tool.briefcase.app.kemonodownloader.iOS]
supported = false

[tool.briefcase.app.kemonodownloader.android]
supported = false

# Web deployments
[tool.briefcase.app.kemonodownloader.web]
supported = false

